### ISSUE TITLE
Items dispayed as green

### ISSUE THREAD

**Issue by Val-rie** [ds5678/Food-Pack#1]
Hi! I encountered a bug where some of the new items get dispayed as green and are non-interactable. I've also seen a couple of black cans with "Random tall drink" text on them, also can't pick those up (I can't remember where I saw them to go back and make a screenshot, sorry!). Some of the new items are working just fine though - from what I've seen so far, cocoa is fully functional and rice seems to be fine too. 
Thanks for your hard work!

![image](https://user-images.githubusercontent.com/84006660/117775607-56939e80-b243-11eb-8def-0d672b7b8477.png)
![image](https://user-images.githubusercontent.com/84006660/117776819-9f982280-b244-11eb-8866-2f91ca9c86f6.png)

**Comment by ds5678** [comment]
Sorry, I didn't see this until now. You probably changed one of the advanced settings in ModComponent. If you set "Disable Random Item Spawns" to No, it should return things to normal behaviour.

**Comment by ds5678** [comment]
By the way, if you have any issues in the future, it's almost always faster to contact me on the modding discord. https://discord.gg/EhBWKRx
