### ISSUE TITLE
Aurora energy drink may cause the buff "fatigue reduced" works wrongly.

### ISSUE THREAD

**Issue by JtheV** [ds5678/Food-Pack#9]
Hi! It seems I encountered a bug.
If I have drinked aurora energy drink added by this mod, I can't get the buff "fatigue reduced" by drinking coffee in this game. Then I can only get this buff by drinking aurora energy drink. The only way to get the buff "fatigue reduced" by drinking coffee (just like vanilla) is starting a new game.
(I've started a new game to test this.)
Thanks for your help!

**Comment by ds5678** [comment]
I do not maintain this mod anymore, and even if I did, it would be an upstream issue with ModComponent.
